version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/modules/container-registry"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/dns-zone"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/firebase"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/ingress"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/secret"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/service-accounts"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/sso-rbac"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/uptime-check"
    schedule:
      interval: "daily"
