name: Checkov
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      discussions: write
      pull-requests: write
      security-events: write
      id-token: write
    strategy:
      matrix:
        path:
          - container-registry
          - dns-zone
          - firebase
          - ingress
          - service-accounts
          - sso-rbac
          - uptime-check
     
    steps:
    - uses: dasmeta/reusable-actions-workflows/checkov@main
      with:
        fetch-depth: 0
        directory: ${{ matrix.path }}
      continue-on-error: true
